### ISSUE TITLE
Build page component (About)

### ISSUE THREAD

**Issue by BolajiAyodeji** [oscommunityafrica/osf-website#10]
This Issue relies on the completion of #2, #3, #4, #6 and #9 

Build a replicate of the About section in a component as seen in the website's [design prototype](https://www.figma.com/proto/IpD33qs3eaRznNKw2wWUQb/OSF-website(high-fidelity)?node-id=394%3A0&scaling=min-zoom)

- Build and style the section
- Fetch media asset from cloudinary

![image](https://user-images.githubusercontent.com/30334776/69575528-b99b6200-0fca-11ea-9e58-0808c243c0cb.png)

**Comment by Olawoore** [comment]
Can you assign this to me? @BolajiAyodeji

**Comment by BolajiAyodeji** [comment]
> Can you assign this to me? @BolajiAyodeji

Yes, please, I just did.

How long will this take you?

**Comment by Olawoore** [comment]
24hrs after the completion of #2, #3, #4, #6 and #9

**Comment by Olawoore** [comment]
I'm I building a replica of what is above? coz the about section on the prototype isn't displaying

**Comment by BolajiAyodeji** [comment]
> I'm I building a replica of what is above? coz the about section on the prototype isn't displaying

Hello @Olawoore, This issue has been fixed in #56.
My apologies, please check for other issues you'll like to work on.
