### ISSUE TITLE
Provide all media && design assets

### ISSUE THREAD

**Issue by BolajiAyodeji** [oscommunityafrica/osf-website#11]
Create a drive with all media assets and link(s) to all designs and prototypes.

**Comment by perriefidelis** [comment]
[style guide](https://www.figma.com/file/wtojDaoY2PJED946ZMIvsX/OSCA-style-guide-pattern)
[webite dev](https://www.figma.com/file/IpD33qs3eaRznNKw2wWUQb/OSF-website-high-fidelity?node-id=0%3A1)
[website prototyope](https://www.figma.com/proto/IpD33qs3eaRznNKw2wWUQb/OSF-website-high-fidelity?node-id=0%3A1&scaling=min-zoom)

**Comment by BolajiAyodeji** [comment]
@allcontributors please add @perriefidelis for design

**Comment by BolajiAyodeji** [comment]
@perriefidelis can you please provide the GitHub username(s) of all the designers who worked on this project or rather ask them to comment under this thread?

So we can appreciate them on the README.md

**Comment by perriefidelis** [comment]
> @perriefidelis can you please provide the GitHub username(s) of all the designers who worked on this project or rather ask them to comment under this thread?
> 
> So we can appreciate them on the README.md

@BolajiAyodeji add @mrstevea and @legendaryofor as contributors!

**Comment by BolajiAyodeji** [comment]
@allcontributors please add @mrstevea for design

**Comment by BolajiAyodeji** [comment]
@allcontributors please add @legendaryofor for design
