### ISSUE TITLE
Build the style guide (Component: Button)

### ISSUE THREAD

**Issue by BolajiAyodeji** [oscommunityafrica/osf-website#14]
The design team has built the Style guide, which can be found [here](https://www.figma.com/file/wtojDaoY2PJED946ZMIvsX/OSCA-style-guide%2Fpattern).

This issue is a chunk of #4, ensure to check it first.

- Build the button components similar to the design and document all classes used
- Build with great focus on all states and responsiveness.

**Comment by BolajiOlajide** [comment]
Assign me, sir @BolajiAyodeji .

**Comment by BolajiAyodeji** [comment]
Just assigned you chief :fire:

**Comment by BolajiOlajide** [comment]
I'm setting up `storybook` as part of this ticket since that is needed to view the components in isolation.

**Comment by BolajiOlajide** [comment]
Also, the Figma link displays 404.

**Comment by BolajiAyodeji** [comment]
> Also, the Figma link displays 404.

@perriefidelis we need the Figma link here too

**Comment by BolajiAyodeji** [comment]
> I'm setting up `storybook` as part of this ticket since that is needed to view the components in isolation.

Alright chief, sounds great.

**Comment by BolajiAyodeji** [comment]
@BolajiOlajide the Figma link is updated now, please check now.

**Comment by BolajiOlajide** [comment]
@BolajiAyodeji PR ready.
