### ISSUE TITLE
Build the style guide (Components: Dropdown and SearchBar)

### ISSUE THREAD

**Issue by BolajiAyodeji** [oscommunityafrica/osf-website#15]
The design team has built the Style guide, which can be found [here](https://www.figma.com/file/wtojDaoY2PJED946ZMIvsX/OSCA-style-guide%2Fpattern).

This issue is a chunk of #4, ensure to check it first.

- Build the Dropdown and SearchBar component similar to the design and document all classes used
- Build with great focus on all states and responsiveness.

**Comment by ashinzekene** [comment]
Assign to me
