### ISSUE TITLE
Build the style guide (Components: Checkboxes)

### ISSUE THREAD

**Issue by BolajiAyodeji** [oscommunityafrica/osf-website#18]
The design team has built the Style guide, which can be found [here](https://www.figma.com/file/wtojDaoY2PJED946ZMIvsX/OSCA-style-guide%2Fpattern).

This issue is a chunk of #4, ensure to check it first.

- Build the Checkboxes components similar to the design and document all classes used
- Build with great focus on all states and responsiveness.

**Comment by fakela** [comment]
@BolajiAyodeji I will look into this from tommorow
