### ISSUE TITLE
Build the style guide (Components: Radio Button)

### ISSUE THREAD

**Issue by BolajiAyodeji** [oscommunityafrica/osf-website#19]
The design team has built the Style guide, which can be found [here](https://www.figma.com/file/wtojDaoY2PJED946ZMIvsX/OSCA-style-guide%2Fpattern).

This issue is a chunk of #4, ensure to check it first.

- Build the Radio Button components similar to the design and document all classes used
- Build with great focus on all states and responsiveness.

**Comment by fakela** [comment]
@BolajiAyodeji can this task be assigned to me

**Comment by BolajiAyodeji** [comment]
Yes, please. I just assigned you to it.
