### ISSUE TITLE
Setup Tailwind theme configuration

### ISSUE THREAD

**Issue by BolajiAyodeji** [oscommunityafrica/osf-website#2]
Set up the workflow of using Tailwind with our components and overriding Tailwind default properties.

- Set up Tailwind base styles and prefixes to be used to build our components
- Configure the workflow of using Tailwind to build our custom CSS classes or partials

Useful resources:
- https://tailwindcss.com/course/customizing-your-design-system/
- https://tailwindcss.com/docs/configuration
- https://tailwindcss.com/docs/theme

**Comment by alabobriggs** [comment]
Please can I be assigned to this.

**Comment by BolajiAyodeji** [comment]
> Please can I be assigned to this.

Yes, please. I just assigned you this task.

How long will this take you?

**Comment by fakela** [comment]
@alabobriggs  are you already working on this

**Comment by alabobriggs** [comment]
Yes I am @fakela

**Comment by alabobriggs** [comment]
10:30pm today it should be done @BolajiAyodeji

**Comment by BolajiAyodeji** [comment]
> 10:30pm today it should be done @BolajiAyodeji

Alright, thanks for the update.

**Comment by alabobriggs** [comment]
@BolajiAyodeji is there an existing prefix that should be used?
Am I to add the color schemes provided in the design?

**Comment by BolajiAyodeji** [comment]
> @BolajiAyodeji is there an existing prefix that should be used?
> Am I to add the color schemes provided in the design?

What ideas of prefixes do you have in mind?
Yes, please, add the schemes defined in the style guide.

**Comment by alabobriggs** [comment]
> > @BolajiAyodeji is there an existing prefix that should be used?
> > Am I to add the color schemes provided in the design?
> 
> What ideas of prefixes do you have in mind?
> Yes, please, add the schemes defined in the style guide.

osca. id this Too long. Is it very necessary?.

okay I will add that

**Comment by alabobriggs** [comment]
@BolajiAyodeji please where can I find the style guide. I have checked the design but I can't find any.

**Comment by alabobriggs** [comment]
@BolajiAyodeji please a link to the styleguide. The one [here](https://www.figma.com/file/vO0aThJUcmB7VhsxW66q7h/Style-guide?node-id=4%3A98) isn;t available

**Comment by BolajiAyodeji** [comment]
> > > @BolajiAyodeji is there an existing prefix that should be used?
> > > Am I to add the color schemes provided in the design?
> > 
> > 
> > What ideas of prefixes do you have in mind?
> > Yes, please, add the schemes defined in the style guide.
> 
> osca. is this Too long. Is it very necessary?.
> 
> okay I will add that

You can use `oc`, this is shorter.
What do you thunk?

**Comment by alabobriggs** [comment]
> > > > @BolajiAyodeji is there an existing prefix that should be used?
> > > > Am I to add the color schemes provided in the design?
> > > 
> > > 
> > > What ideas of prefixes do you have in mind?
> > > Yes, please, add the schemes defined in the style guide.
> > 
> > 
> > osca. is this Too long. Is it very necessary?.
> > okay I will add that
> 
> You can use `oc`, this is shorter.
> What do you thunk?

okay. This is good.

**Comment by BolajiAyodeji** [comment]
@perriefidelis we need a link to the style guide that is accessible to everyone please

**Comment by alabobriggs** [comment]
@BolajiAyodeji please is there an update yet

**Comment by BolajiAyodeji** [comment]
> @BolajiAyodeji please is there an update yet

Yes @alabobriggs, kindly check #11 for all links.

**Comment by alabobriggs** [comment]
@BolajiAyodeji 

> > @BolajiAyodeji please is there an update yet
> 
> Yes @alabobriggs, kindly check #11 for all links.

Okay. I'll look at it and update as soon as possible

**Comment by BolajiAyodeji** [comment]
> @BolajiAyodeji
> 
> > > @BolajiAyodeji please is there an update yet
> > 
> > 
> > Yes @alabobriggs, kindly check #11 for all links.
> 
> Okay. I'll look at it and update as soon as possible

Any updates, please?

**Comment by alabobriggs** [comment]
Yes. I am on it now 

> > @BolajiAyodeji
> > > > @BolajiAyodeji please is there an update yet
> > > 
> > > 
> > > Yes @alabobriggs, kindly check #11 for all links.
> > 
> > 
> > Okay. I'll look at it and update as soon as possible
> 
> Any updates, please?

**Comment by alabobriggs** [comment]
@BolajiAyodeji I need help with naming of the color show on the [styleguid](https://www.figma.com/file/wtojDaoY2PJED946ZMIvsX/OSCA-style-guide%2Fpattern?node-id=62%3A63) .

**Comment by BolajiAyodeji** [comment]
> @BolajiAyodeji I need help with naming of the color show on the [styleguide](https://www.figma.com/file/wtojDaoY2PJED946ZMIvsX/OSCA-style-guide%2Fpattern?node-id=62%3A63) .

Let's have a quick sync?

**Comment by alabobriggs** [comment]
> > @BolajiAyodeji I need help with naming of the color show on the [styleguide](https://www.figma.com/file/wtojDaoY2PJED946ZMIvsX/OSCA-style-guide%2Fpattern?node-id=62%3A63) .
> 
> Let's have a quick sync?

Thank you. Might have found a way now. Will keep you updated

**Comment by BolajiAyodeji** [comment]
Alright, I would be glad if this is ready by tomorrow, #25 is relying on the implementation of this. Keep me posted please

**Comment by alabobriggs** [comment]
@BolajiAyodeji just created a pull request [here](https://github.com/oscommunityafrica/osf-website/pull/26#issue-346832129)
