### ISSUE TITLE
Build the style guide (Components: Selector)

### ISSUE THREAD

**Issue by BolajiAyodeji** [oscommunityafrica/osf-website#20]
The design team has built the Style guide, which can be found [here](https://www.figma.com/file/wtojDaoY2PJED946ZMIvsX/OSCA-style-guide%2Fpattern).

This issue is a chunk of #4, ensure to check it first.

- Build the Selector components similar to the design and document all classes used
- Build with great focus on all states and responsiveness.

**Comment by BolajiOlajide** [comment]
Hey @BolajiAyodeji ,

what's the difference between a `Selector` and a `Checkbox/Radio` button?

**Comment by BolajiAyodeji** [comment]
> Hey @BolajiAyodeji ,
> 
> what's the difference between a `Selector` and a `Checkbox/Radio` button?

It's actually the same thing, just some border radius for the selector according to the style guide. The design team separated it so I thought to create an issue for it with level simple. Looks like the easiest ticket :sweat_smile:

**Comment by BolajiOlajide** [comment]
Yes, I get that. I'm having a hard time figuring out the difference between what a selector does and what a Checkbox / Radio button helps us achieve? I might be overthinking it, but I'll probably pick another ticket.

**Comment by BolajiAyodeji** [comment]
I'll have to cc @perriefidelis again here so the design team can explain better.

I want to believe, the Checkbox actually allows the user to select an option, the comparison should be between the Checkbox and Radio buttons and maybe there shouldn't be a `Selector` component after all. I'll get back to this with more context from the design team, please feel free to pick another ticket.

**Comment by BolajiOlajide** [comment]
Yeah, for a bit of context @perriefidelis.

Since the checkbox and radio components act as selectors for multiple and single entities respectively, I'm uncertain the value the `selector` component will add since both components listed above already helps us achieve this.

**Comment by BolajiAyodeji** [comment]
Sorry for the delays with this. I got word from the design team that the style guide is actually not just for the website but also for their general designs so some components are actually not meant for dev.

I'll be closing this issue for now and apologies for the confusion.
