### ISSUE TITLE
Build the style guide (Components: Tab)

### ISSUE THREAD

**Issue by BolajiAyodeji** [oscommunityafrica/osf-website#23]
The design team has built the Style guide, which can be found [here](https://www.figma.com/file/wtojDaoY2PJED946ZMIvsX/OSCA-style-guide%2Fpattern).

This issue is a chunk of #4, ensure to check it first.

- Build the Tab components similar to the design and document all classes used
- Build with great focus on all states and responsiveness.

**Comment by ashinzekene** [comment]
Hey. Am I free to contribute?

**Comment by BolajiAyodeji** [comment]
Yes, please. I just assigned you to this.

How long will it take you, please?

**Comment by ashinzekene** [comment]
I'd see if I get it ready latest Wed. Fine?

**Comment by BolajiAyodeji** [comment]
Alright, thank you.
