### ISSUE TITLE
Build the style guide (Components: Pagination)

### ISSUE THREAD

**Issue by BolajiAyodeji** [oscommunityafrica/osf-website#36]
The design team has built the Style guide, which can be found [here](https://www.figma.com/file/wtojDaoY2PJED946ZMIvsX/OSCA-style-guide%2Fpattern).

This issue is a chunk of #4, ensure to check it first.

- Build the Pagination component similar to the design and document all classes used
- Build with great focus on all states and responsiveness.

**Comment by ashinzekene** [comment]
Assign me 🍾

**Comment by BolajiAyodeji** [comment]
> Assign me 
> 
> Also, what implementation are we using?
> Examples are Google, Amazon.
> 
> What numbers are shown when for eg, the current page is 7 and there are 15 pages?

I just assigned you.
Kindly check the [Style guide](https://www.figma.com/file/wtojDaoY2PJED946ZMIvsX/OSCA-style-guide%2Fpattern) for the required implementation.

**Comment by ashinzekene** [comment]
> > Assign me
> > Also, what implementation are we using?
> > Examples are Google, Amazon.
> > What numbers are shown when for eg, the current page is 7 and there are 15 pages?
> 
> I just assigned you.
> Kindly check the [Style guide](https://www.figma.com/file/wtojDaoY2PJED946ZMIvsX/OSCA-style-guide%2Fpattern) for the required implementation.

It doesn't really say

**Comment by BolajiAyodeji** [comment]
Alright, we are doing something similar to Google's.
I'll cc @perriefidelis on this.

**Comment by ashinzekene** [comment]
Alright

**Comment by perriefidelis** [comment]
we can close this up ... once the PR is merged
