### ISSUE TITLE
Setup Tests for components

### ISSUE THREAD

**Issue by BolajiAyodeji** [oscommunityafrica/osf-website#7]
Setup and document tests for all components. These tests should test the functionality of the app and mimic how it will be used by end-users based on the design prototype.

```
Many integration tests. No snapshot tests. Few unit tests. Few end to end tests.
```

Proposed tools: [Jest](https://jestjs.io/) or [Cypress](https://www.cypress.io/)

Useful guide(s):
- https://reactjs.org/docs/testing.html
- https://www.gatsbyjs.org/docs/testing-react-components/
- https://flaviocopes.com/react-testing-components/

**Comment by NotJohs** [comment]
I would like to look into this.

**Comment by BolajiAyodeji** [comment]
> I would like to look into this.
> @BolajiAyodeji Can I be assigned this task?

Yes, please. I just assigned you to it.

**Comment by BolajiAyodeji** [comment]
Keep me posted please and work on one PR with clear commit messages.
Let me know if you need any help or clarification, cheers!

**Comment by BolajiAyodeji** [comment]
Hey @NotJohs, I forgot to mention: before you pick an issue you have to let us know the estimated number of hours you can take to finish the task.

How long will this take you? we have just limited time.

**Comment by NotJohs** [comment]
Hello @BolajiAyodeji, I can complete this issue today. 

Based on the requirement for this issue, We would be using the `Cypress` testing framework for integration tests and `Jest` library for Unit tests.
