### ISSUE TITLE
Typo in website scholarship page

### ISSUE THREAD

**Issue by NdibeRaymond** [oscommunityafrica/osf-website#72]
**Page Affected**
https://festival.oscafrica.org/scholarship/

**Explanation**
In the field that says "Do you hold a valid passport?", the next line says, "Note: For locals, please indicate with "Not Applicable", if you are living Nigeria."
the word "in" is missing between "living" and "Nigeria".

**Comment by BolajiAyodeji** [comment]
Hi @NdibeRaymond, thank you for raising this issue. It's fixed now. :1st_place_medal:

**Comment by BolajiAyodeji** [comment]
@all-contributors please add @NdibeRaymond for content
