### ISSUE TITLE
test

### ISSUE THREAD

**Issue by BolajiAyodeji** [oscommunityafrica/osf-website#74]
test

**Comment by joshikeno** [comment]
@BolajiAyodeji Please, reopen this issue.
We can create task for this test. 
I would primarily be handling majority of this (test) issue but any volunteers would be appreciated.

**Comment by BolajiAyodeji** [comment]
> @BolajiAyodeji Please, reopen this issue.
> We can create task for this test.
> I would primarily be handling majority of this (test) issue but any volunteers would be appreciated.

This issue was opened to actually test the "issues welcome message" action, hence me closing immediately.

Let me know the kind of issues you want to create related to testing and I'll help you.
