### ISSUE TITLE
Setup CI && coveralls for Tests

### ISSUE THREAD

**Issue by BolajiAyodeji** [oscommunityafrica/osf-website#8]
This issue relies on the completion of #7 

Setup continuous integration to keep track of all tests and coverall to give a coverage report of how much of our code is being tested.

**Comment by NotJohs** [comment]
@BolajiAyodeji  since this issue is related to #7 I would look into this.

**Comment by BolajiAyodeji** [comment]
Sure, I've assigned you to it now.

**Comment by BolajiAyodeji** [comment]
Keep me posted please and work on one PR with clear, concise and descriptive commit messages.
Let me know if you need any help or clarification, cheers!

**Comment by NotJohs** [comment]
@BolajiAyodeji I need a maintainer/contributor privilege to include `Circle CI` into this project.

**Comment by NotJohs** [comment]
@BolajiAyodeji 

The following tools need to be integrated into the repo: 
* Github Market place:
  * circleci
  * coverall
  * pre-commit
  * cypress
* [cypress project integration](https://docs.cypress.io/guides/dashboard/introduction.html#Features).
In other to record test and coverage result using the dashboard we need to create an organization and generate a project key which can be used with `cypress.yml`.
 
These steps are very important for generating code coverage and CI.

**Comment by BolajiAyodeji** [comment]
> @BolajiAyodeji
> 
> The following tools need to be integrated into the repo:
> 
> * Github Market place:
>   
>   * circleci
>   * coverall
>   * pre-commit
> * [cypress project integration](https://docs.cypress.io/guides/dashboard/introduction.html#Features).
>   In other to record test and coverage result using the dashboard we need to create an organization and generate a project key which can be used with `cypress.yml`.
> 
> These steps are very important for generating code coverage and CI.

Can you add links to all of them, please?

**Comment by NotJohs** [comment]
@BolajiAyodeji updated.

**Comment by joshikeno** [comment]
@BolajiAyodeji this can be closed.
